### ISSUE TITLE
eos.contract doesn't work, account_missing error

### ISSUE THREAD

**Issue by ene5135** [EOSEssentials/Scatter#60]
eos : dawn4.2
scatter : 4.0.3

when I call eos.contract, it gives account_missing error.
I think code is correct...
and I set all scatter things correctly. (identity, key pair, account...)
Is it just version missmatch problem?
or should I modify the code?

code :
``` JavaScript

const eosOptions = {};
const eos = scatter.eos( network, Eos.Localnet, eosOptions );
scatter.getIdentity({ accounts:[network] }).then(id => {
  const account = id.accounts.find(account => account.blockchain === 'eos');
  const options = {
                          authorization: [
                              `${account.name}@${account.authority}`,
                          ]
                      };

  eos.contract(MY_CONTRACT).then(contract => {
      contract.myAction(...args, options);
  })
})
```

error :

`{type: "account_missing", message: "Missing required accounts, repull the identity", code: 402, isError: true}
code
:
402
isError
:
true
message
:
"Missing required accounts, repull the identity"
type
:
"account_missing"`

**Comment by mlockett42** [comment]
I had a similar error when pushing to the delegatebw system contact.

You might be using the @owner authority when you need to use the @active authority

**Comment by iFrankWu** [comment]
I got the issue too,  did u figure it out?

**Comment by ene5135** [comment]
thanks for your answer @mlockett42 , but I used @active authority correctly.
similar code works well using eosjs only (without scatter)
I'm still stuck in this problem

**Comment by nsjames** [comment]
There's two cases which could return this error.

The account specified is not attached to the network specified
https://github.com/EOSEssentials/Scatter/blob/master/src/services/SignatureService.js#L62

The `name@permission` is incorrect or not included in the `messages.authorization` from the EOS transaction when collected.
https://github.com/EOSEssentials/Scatter/blob/master/src/services/SignatureService.js#L72

```
payload.messages
    .map(message => message.authorization
        .map(auth => `${auth.actor}@${auth.permission}`))
```
It's possible something has changed with the latest eosjs or EOSIO. I am pulling latest master and checking.

**Comment by iFrankWu** [comment]
@nsjames Did you figure out the issue? this issue has block my job, I would like u can make a fix strongly. thanks a lot.

**Comment by ene5135** [comment]
I found the reason. 
error occurred here,
https://github.com/EOSEssentials/Scatter/blob/master/src/services/SignatureService.js#L62 

I found that I missed chainId field when I call scatter.suggestNetwork() function. 
But I set chainId when I call scatter.eos(). 
So this made missmatch in [networkedAccount()](https://github.com/EOSEssentials/Scatter/blob/master/src/services/SignatureService.js#L60) function.

code
``` JavaScript
scatter.suggestNetwork({blockchain: 'eos', host:'127.0.0.1', port:8888, })
// "eos:127.0.0.1:8888" made by .unique() 
...
scatter.eos({blockchain: 'eos', host:'127.0.0.1', port:8888, chainId:1 || 'abcd',}, Eos.Localnet, {})
// "eos:chain:1" made by .unique()
```

the easiest way to solve the problem was remove chainId field both calling scatter.suggestNetwork() and scatter.eos()

``` JavaScript
scatter.suggestNetwork({blockchain: 'eos', host:'127.0.0.1', port:8888, })
// "eos:127.0.0.1:8888" made by .unique() 
...
scatter.eos({blockchain: 'eos', host:'127.0.0.1', port:8888,}, Eos.Localnet, {})
// "eos:127.0.0.1:8888" made by .unique()

```

It was just my minor mistake. 

thank you @nsjames!
and try this @iFrankWu

**Comment by iFrankWu** [comment]
Thanks  a lot @nsjames @ene5135 , finally I also fixed it too.

It is required pass the network to scatter to get eos instance.

![image](https://user-images.githubusercontent.com/6120669/40892068-15e5e7de-67c4-11e8-9662-6cebf6b2bfc9.png)

**Comment by nsjames** [comment]
So I think there should be a fix internally for Scatter relating to this.

It should go down the stack of the network looking for possible accounts within the specified identity.

Flow:
1) Search for account with chain ID ||
2) Search for account with host:port ||
3) Search for account with host

Possibly even omitting step 2 as it is redundant.

**Comment by kasperfish** [comment]
yes please fix his... too many chainid mismatches... it would be nice that we only need to setup the connection in one object...

**Comment by alexpmorris** [comment]
I had so many issues getting this to work due to all the outdated examples.

Just wanted to share what finally worked for me, for use with the jungle testnet.  This example demonstrates multiple transfers wrapped into a single transaction.

However, issue still remains that you can't access http from an https site.  If anyone knows of an active https rpc-node for jungle testnet, please share! :)

```
var network = {blockchain:'eos', protocol: "http", host: 'ayeaye.cypherglass.com', port:8888, chainId:'038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca'}

scatter.getIdentity({accounts:[network]}).then(identity=>{ 
  const account = identity.accounts.find(acc=>acc.blockchain==='eos'); 
  const eos = window.scatter.eos(network, Eos, {broadcast:true, chainId:'038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca'}, "http"); 
  const requiredFields = {accounts:[network]};
  eos.contract('eosio.token', {requiredFields}).then(contract => {
    contract.transaction(tx => {
      tx.transfer('abcabcabc123', 'abcabcabc321', '1.1234 EOS', '');
      tx.transfer('abcabcabc123', 'abcabcabc321', '1.4321 EOS', '');
    }).then(trx => { console.log("trx", trx); });
  });
});
```
